package org.example.naumenteststgbot.enums;

/**
 * Перечисление состояний пользователя в системе
 */
public enum UserState {
    DEFAULT,
    ADD_QUESTION,
    ADD_TEST_TITLE,
    ADD_TEST_DESCRIPTION,
    EDIT_TEST,
    EDIT_TEST_TITLE,
    CHOOSE_DELETE_TEST,
    DELETE_TEST,
    CONFIRM_DELETE_TEST,
    EDIT_TEST_DESCRIPTION,
    ADD_QUESTION_TEXT,
    ADD_ANSWER,
    DELETE_QUESTION,
    CONFIRM_DELETE_QUESTION,
    SET_CORRECT_ANSWER,
    EDIT_QUESTION,
    EDIT_QUESTION_TEXT,
    EDIT_ANSWER_OPTION_CHOICE,
    EDIT_ANSWER_TEXT_CHOICE,
    EDIT_ANSWER_TEXT,
    VIEW_TEST,
    EDIT_ANSWER_OPTION
}
